# Generated by Django 5.1.8 on 2025-04-27 02:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('unit_type', models.CharField(choices=[('ml', 'Milliliters'), ('unit', 'Unit')], max_length=50)),
                ('product_type', models.CharField(choices=[('supply', 'Supply'), ('accessory', 'Accessory')], max_length=50)),
                ('last_purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_control_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.profile')),
            ],
        ),
    ]
