name: Lint with flake8

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r django_core/requirements.txt
          pip install flake8

      - name: Run flake8
        run: |
          flake8 django_core/ --count --select=E9,F63,F7,F82 --show-source --statistics