name: Run Pytest

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.12.1
        uses: actions/setup-python@v2
        with:
          python-version: "3.12.1"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r django_core/requirements.txt

      - name: Test with pytest
        working-directory: ./django_core
        run: pytest -vv

      - name: Run tests with coverage
        working-directory: ./django_core
        run: |
          pytest -vv --cov=. --cov-report=xml --cov-fail-under=90